### ISSUE TITLE
withArchive() HOC not passing new archive ID to handler.fetchArchive after receiving new props

### ISSUE THREAD

**Issue by janicak** [humanmade/repress#19] opened 2018-04-30 05:50 UTC
When a ```withArchive```-wrapped component receives new props that necessitate a change to the archive ID, such as a change in route, how do you handle fetching the new post(s) if needed? It seems like the HOC's ```props.onLoad``` function might be using a ```resolvedId``` argument evaluated when the component initializes, so not sure how to get the new ID to ```handler.fetchArchive``` when the component is updating.

**Comment by rmccue** [comment] 2018-04-30 05:52
The HOC's [`componentWillReceiveProps` lifecycle hook](https://github.com/humanmade/repress/blob/b49767ebe777aaad246507970602990df74b3a92/src/withArchive.js#L17-L20) should be handling this for you already. The ID is resolved in `mapStateToProps`, which is called on every render.

**Comment by janicak** [comment] 2018-04-30 07:16
```mapStateToProps``` looks like it updates ```props._data.archiveId``` but not ```props._actions.onLoad```. I'm able to get it to work in part like so...

**withArchive.js:**
```diff
...
componentWillReceiveProps( nextProps ) {
  if ( ! nextProps._data.posts && this.props._data.archiveId !== nextProps._data.archiveId ) {
-    nextProps._actions.onLoad();
+    nextProps._actions.onLoadId(nextProps._data.archiveId, nextProps );
  }
}
...
const mapDispatchToProps = ( dispatch, props ) => {
  const resolvedId = resolve( id, props );
  return {
    _actions: {
      onLoad:     () => dispatch( handler.fetchArchive( resolvedId ) ),
+     onLoadId: (id, props) => dispatch( handler.fetchArchive( resolve(id, props))),
      onLoadMore: page => dispatch( handler.fetchMore( getSubstate, resolvedId, page ) ),
    },
  };
};
```
***Page.js:***
```javascript
import React from 'react';

import { pages, normalizePath, SITE_HOME } from '../reducers/wp_types';
import { withArchive } from '../lib/repress/src/index.js';

const Page = props => {
  const { loading, posts, archiveId } = props;
  const path = archiveId.replace('_page', '');
  if ( loading ) {
    return <p>Loading</p>;
  }
  if ( ! posts ) {
    return <p>404</p>;
  }
  const page = posts.find( post => post.link === SITE_HOME + path + '/' );
  if ( ! page ) {
    return <p>Also 404</p>;
  }
  return (
    <div className="Page">
      <h1 dangerouslySetInnerHTML={ { __html: page.title.rendered } }/>
    </div>
  );
};

export default withArchive(
  pages,
  state => state.pages,
  props => {
    let path = normalizePath(props.location.pathname);
    if (props.history.action === 'PUSH'){
      path = normalizePath(props.history.location.pathname);
    }
    const id = `_page/${ path }`;
    const slug = path.split( '/' ).slice( -1 )[0];
    pages.registerArchive( id, {
      type: 'page',
      slug
    } );
    return id;
  }
)(Page);
```

... although for some reason ```props.posts``` has  a maximum of two posts, with the previous post at ```props.posts[-1] ```, and some of the other props aren't updated.

**Comment by janicak** [comment] 2018-04-30 09:13
> Do you have a simple example of what's not working?

```
> git clone https://github.com/janicak/repress-issue.git repress-issue
> cd repress-issue
> npm run start
```
Navigate to http://localhost:3000/about-our-center/introduction/ and click any of the links.

**Comment by janicak** [comment] 2018-05-02 09:53
I'm not seeing the ```withArchive``` HOC's ```mapDispatchToProps``` being called upon an update to props via redux store change (using Chrome inspector). Possibly related issues:

- https://github.com/reactjs/react-redux/issues/535
- https://github.com/reactjs/react-redux/issues/810

However, ```mapStateToProps``` _is_ being called when changes to the redux store triggers new prop updates, so calling a version of ```nextProps._actions.onLoad``` from  ```componentWillReceiveProps``` where you can pass a new id seems to work fine.

**withArchive.js:**
```diff
...
componentWillReceiveProps( nextProps ) {
  if ( ! nextProps._data.posts && this.props._data.archiveId !== nextProps._data.archiveId ) {
-    nextProps._actions.onLoad();
+    nextProps._actions.onLoad(nextProps._data.archiveId, nextProps );
  }
}
...
const mapDispatchToProps = ( dispatch, props ) => {
- const resolvedId = resolve( id, props );
  return {
    _actions: {
-     onLoad: () => dispatch( handler.fetchArchive( resolvedId ) ),
+     onLoad: (id, props) => dispatch( handler.fetchArchive( resolve(id, props))),
      onLoadMore: page => dispatch( handler.fetchMore( getSubstate, resolvedId, page ) ),
    },
  };
};
```

**Comment by rmccue** [comment] 2018-05-03 02:30
Sorry for the delay here, looking into it now.

Right now, I'm suspecting that there's an issue somewhere else in the code. I've replaced the whole `Page` component with:
```js
export default props => {
  console.log( 'render' );
  return <p>Render</p>;
};
```

The router correctly redirects, however the paragraph never renders, so I'm wondering if there's an issue in the router instead. I'll continue digging.

**Comment by rmccue** [comment] 2018-05-03 02:57
Wrapping the top-level component in `withRouter` fixes the redirection issue; still investigating the rest.

```diff
diff --git a/src/index.js b/src/index.js
index 31fc06c..2b7c4f2 100644
--- a/src/index.js
+++ b/src/index.js
@@ -6,7 +6,7 @@ import { Provider, connect } from 'react-redux';
 import configureStore from './store/configureStore';
 
 import { ConnectedRouter } from 'react-router-redux'
-import { Route, Switch, Redirect } from 'react-router';
+import { Route, Switch, Redirect, withRouter } from 'react-router';
 import history from './store/routerHistory';
 
 import Page from './components/Page';
@@ -24,9 +24,9 @@ const AppContainer = () => (
   </ConnectedSwitch>
 );
 
-const App = hot(module)(connect(state => ({
+const App = hot(module)(withRouter(connect(state => ({
   location: state.location,
-}))(AppContainer));
+}))(AppContainer)));
 
 const store = configureStore();
 
```

**Comment by rmccue** [comment] 2018-05-03 03:10
OK, further investigation has revealed the problem.

1. When the page navigates, an action is dispatched to the store. This is then reduced into a change in the store by react-router-redux's reducer.
2. When the store is updated, react-redux calls [handleNewState](https://github.com/reactjs/react-redux/blob/57128d5a20d15f43513acd13251465966426d956/src/connect/selectorFactory.js#L63-L72).
3. `handleNewState` calls `mapStateToProps` but not `mapDispatchToProps`; `mapDispatchToProps` doesn't receive `state`, so it's stable between changes to the store.
4. Your `mapPropsToId` function receives the props, which have not changed
5. Your `mapPropsToId` reads `props.history` which **has** changed underneath us

So, the fundamental issue is that react-router-redux is mutating `props.history` without replacing the object. (This might be a bug in react-router-redux@5) This causes the prop equivalence check to pass, leading react-redux to skip re-rendering. However, it causes your `mapPropsToId` function to return a different value.

Now, the good news: it looks like the prop equivalence check that's problematic is the one all the way up at the root, so the above fix to add `withRouter` appears to fix both the redirection issue from `/` as well as the loading issues. Additionally, it means you can remove the `props.history.action === 'PUSH'` hack from your `mapPropsToId`.

https://github.com/janicak/repress-issue/pull/1 contains the diff that should get this working for you.

Closing, as this is not a bug in Repress, rather just a very weird side effect of react-router-redux's implementation. :)

**Closed by rmccue** 2018-05-03 03:10 UTC

**Comment by rmccue** [comment] 2018-05-03 03:13
(By the way, thanks for the great example of the bug, it really helped with debugging. Let me know if you launch the site with Repress too!)
